[package]
name = "my_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2.0.98"       # Parsing the Rust code
quote = "1.0"     # Generating the code
proc-macro2 = "1.0"  # Working with token streams

[lib]
proc-macro = true  # This allows you to create a procedural macro